this.pagejs=e=>{(()=>{"use strict";const t="vault"in e;if(t&&void 0===e.vault)throw"Invalid vault";const n=e.vault=e.vault||(e=>{const t=Object.call,n=t.bind(t),o=Object.getOwnPropertyDescriptor;return{__proto__:null,sourceWindow:e,F_c:n,F_a:Object.apply,F_b:Object.bind,F_tS:Function.toString,A_fE:[].forEach,A_so:[].some,A_sh:[].shift,A_j:[].join,A_po:[].pop,A_f:[].filter,A_iO:[].indexOf,A_iA:Array.isArray,O_a:Object.assign,O_k:Object.keys,O_v:Object.values,O_dP:Object.defineProperties,
O_dPy:Object.defineProperty,O_hOP:Object.hasOwnProperty,O_gOPN:Object.getOwnPropertyNames,O_gOPD:o,O_gOPDs:Object.getOwnPropertyDescriptors,O_gPO:Object.getPrototypeOf,O_tS:{}.toString,J_p:JSON.parse,J_s:JSON.stringify,M_f:Math.floor,M_r:Math.random,M_m:Math.max,M_i:MutationEvent.prototype.initMutationEvent,M_pA:MutationEvent.prototype.ADDITION,M_pAT:MutationEvent.AT_TARGET,N_tS:(0).toString,N_MSI:Number.MAX_SAFE_INTEGER,P_t:Promise.prototype.then,P_c:Promise.prototype.catch,
R_rABS:FileReader.prototype.readAsBinaryString,R_rAT:FileReader.prototype.readAsText,R_r:o(FileReader.prototype,"result").get,R_enq:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.enqueue:null,R_cl:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.close:null,S_fCC:String.fromCharCode,S_sl:"".slice,S_su:"".substr,S_sp_nr:"".split,S_iO:"".indexOf,S_tr:"".trim,S_r_nr:"".replace,S_rA_nr:"".replaceAll,S_cCA:"".charCodeAt,S_tLC:"".toLowerCase,
S_tUC:"".toUpperCase,Y_tST:Symbol.toStringTag,D_pFS:DOMParser.prototype.parseFromString,U_cOU:URL.createObjectURL,U_rOU:URL.revokeObjectURL,X_o:XMLHttpRequest.prototype.open,X_pSD:XMLHttpRequest.prototype.DONE,X_pSH:XMLHttpRequest.prototype.HEADERS_RECEIVED,X_pSL:XMLHttpRequest.prototype.LOADING,X_pSO:XMLHttpRequest.prototype.OPENED,X_pSU:XMLHttpRequest.prototype.UNSENT,X_s:XMLHttpRequest.prototype.send,D_n:Date.now,I_tS:e=>""+e,E_r:Element.prototype.remove,E_s:Element.prototype.setAttribute,
D_cS:o(Document.prototype,"currentScript").get,D_gRS:o(Document.prototype,"readyState").get,D_cE:Document.prototype.createElementNS,D_gEBT:Document.prototype.getElementsByTagName,M_aN:o(MutationEvent.prototype,"attrName").get,M_rN:o(MutationEvent.prototype,"relatedNode").get,C_d:o(CustomEvent.prototype,"detail").get,W_aEL:addEventListener,W_rEL:removeEventListener,parseInt,parseFloat,CustomEvent,CompositionEvent,KeyboardEvent,MouseEvent,MutationEvent,MutationObserver,
console:Object.assign({},console),Error,Uint8Array,Blob,ReadableStream,Number,String,Proxy,Window,FileReader,DOMParser,XMLHttpRequest,Function,RegExp,Promise,encodeURIComponent,decodeURIComponent,encodeURI,decodeURI,escape,unescape,atob,btoa,setTimeout,clearTimeout,setInterval,clearInterval,postMessage,dispatchEvent,alert,prompt,confirm,close,getElementById:e.Document.prototype.getElementById,createEvent:e.Document.prototype.createEvent,createElement:e.Document.prototype.createElement}
})(e.unsafeWindow),{F_c:o,F_a:r,F_b:s,F_tS:a,A_fE:i,A_so:l,A_sh:c,A_j:u,A_po:d,A_f:g,A_iO:p,A_iA:v,O_a:f,O_k:m,O_v:_,O_dP:M,O_dPy:b,O_hOP:h,O_gOPN:y,O_gOPD:E,O_gOPDs:w,O_gPO:S,O_tS:G,J_p:O,J_s:R,M_f:L,M_r:C,M_m:T,M_i:A,M_pA:I,M_pAT:x,N_tS:D,N_MSI:P,P_t:U,P_c:$,R_rABS:k,R_rAT:F,R_r:N,R_enq:j,R_cl:V,S_fCC:q,S_sl:X,S_su:B,S_iO:H,S_sp_nr:W,S_tr:J,S_rA_nr:K,S_cCA:z,S_tLC:Y,S_tUC:Q,Y_tST:Z,D_pFS:ee,D_cS:te,D_gRS:ne,D_cE:oe,D_gEBT:re,E_r:se,E_s:ae,M_aN:ie,M_rN:le,C_d:ce,U_cOU:ue,U_rOU:de,X_o:ge,X_s:pe,X_pSD:ve,X_pSH:fe,X_pSL:me,X_pSO:_e,X_pSU:Me,D_n:be,I_tS:he,W_aEL:ye,W_rEL:Ee,parseInt:we,parseFloat:Se,console:Ge,encodeURIComponent:Oe,decodeURIComponent:Re,encodeURI:Le,decodeURI:Ce,escape:Te,unescape:Ae,atob:Ie,btoa:xe,postMessage:De,dispatchEvent:Pe,alert:Ue,prompt:$e,confirm:ke,close:Fe,getElementById:Ne,createEvent:je,createElement:Ve,CustomEvent:qe,CompositionEvent:Xe,KeyboardEvent:Be,MouseEvent:He,MutationEvent:We,MutationObserver:Je,Uint8Array:Ke,FileReader:ze,DOMParser:Ye,XMLHttpRequest:Qe,Function:Ze,RegExp:et,Promise:tt,Blob:nt,ReadableStream:ot,Number:rt,String:st,Proxy:at,Window:it}=n,lt=o,ct=r,ut=m,dt=_,gt=f,pt=M,vt=b,ft=y,mt=E,_t=S,Mt=w||(e=>{
const t=St({});for(const n in e)t[n]=mt(e,n);return t}),bt=v,ht=L,yt=C,Et=T,wt=(e,t,n)=>lt(ct,e,t,n),St=e=>gt({__proto__:null},e),Gt=(e,t,n)=>(vt(e,t,St({value:n,configurable:!0,enumerable:!0,writable:!0})),e),Ot=(e,t)=>Ht(e,t)?e[t]:void 0,Rt=(e,t)=>{const n=mt(e,t);return n?St(n).value:void 0},Lt=(e,t)=>{const n=(e,t,o)=>{const r=mt(e,t),s=r?St(r):void 0;let a;return s?s.enumerable?s.value:void 0:--o>=0&&(a=_t(e))?n(a,t,o):void 0};return n(e,t,5)},Ct=e=>{const t=(t,...n)=>wt(e,t,n)
;return Gt(t,"wrappedJSObject",e),t},Tt=()=>e=>Ct(e),At=Ct(s),It=O,xt=e=>{const t=(e,n)=>{let o;if(null===e)o="null";else if("object"==typeof e){if(n){if(-1!=Xt(n,e))throw"Converting circular structure to JSON";Gt(n,n.length,e)}else n=[e];if(bt(e)){let r="";for(let o=0;o<e.length;o++){let s;s=Ht(e,o)?Ot(e,o):Lt(e,o);const a=t(s,n);r+=`${o?",":""}${void 0===a?"null":a}`}o=`[${r}]`}else{let r="";Bt(ut(e),(o=>{const s=t(e[o],n);void 0!==s&&(r+=`${r?",":""}${R(o)}: ${s}`)})),o=`{${r}}`}n.length-=1
}else o=R(e);return o};return t(e)},Dt=e=>{const t=O(e),n=e=>{const t=[];for(let n=0;n<e.length;n++)Gt(t,n,o(e[n]));return t},o=e=>{if(null===e);else if("object"==typeof e){if(bt(e))return n(e);{const t={};return Bt(ut(e),(r=>{const s=e[r];let a;a="object"==typeof s?bt(s)?n(s):o(s):s,Gt(t,r,a)})),t}}return e};return o(t)},Pt=Tt()(l),Ut=(e,t,n,...o)=>{const r=o||[],s=Nt(e,0,t),a=Nt(e,t,n),i=Nt(e,t+n);let l=Vt([],s);return l=Vt(l,r),l=Vt(l,i),St({result:l,removed:a})
},$t=Tt()(c),kt=Tt()(d),Ft=Tt()(g),Nt=(e,t,n)=>{const o=e.length;let r=t||0;if(r>=o)return[];r<0&&(r=Et(0,o+r));let s=void 0===n?o:n;s<0&&(s=Et(0,o+s)),s>o&&(s=o);const a=St({});for(let t=r;t<s;t++)a[t]=Rt(e,t);return dt(a)},jt=Tt()(u),Vt=(e,...t)=>{let n=e.length;const o=St(e);for(let e=0;e<t.length;e++){const r=t[e],s=bt(r)?r:[r];for(let e=0;e<s.length;e++)o[n+e]=Rt(s,e);n+=s.length}return dt(o)},qt=(e,t)=>{let n=e.length||0;return Gt(e,n,t),n++,e.length=n
},Xt=Tt()(p),Bt=Tt()(i),Ht=Tt()(h),Wt=Tt()(W),Jt=Tt()(X),Kt=Ct(G),zt=_t({}),Yt=e=>{const t=St(e),n=ft(t);for(let e=0;e<n.length;e++){const o=n[e],r=t[o];null!==r&&"object"==typeof r&&_t(r)===zt&&(t[o]=Yt(r))}return t},Qt=e=>{const t=Wt(Kt(e)," ");return Jt(jt(Nt(t,1)," "),0,-1)},Zt=(Tt()(a),Tt()(A)),en=I,tn=x,nn=Tt()(D),on=P,rn=async e=>e,sn=Tt()(U),an=Tt()($),ln=Tt()(k),cn=Tt()(F),un=Tt()(N),dn=j?Tt()(j):j,gn=V?Tt()(V):V,pn=q,vn=Tt()(B),fn=Tt()(H),mn=Tt()(J),_n=(Tt()(K||function(e,t){
return jt(Wt(this,e),t)}),Tt()(z)),Mn=Tt()(Y),bn=Tt()(Q),hn=Z,yn=Ct(ee),En=Ct(te),wn=Ct(ne),Sn=(Ct(oe),Ct(re),Ct(se)),Gn=Ct(ae),On=Ct(ie),Rn=Ct(le),Ln=Ct(ce),Cn=(Tt()(ge),ve),Tn=fe,An=me,In=_e,xn=Me,Dn=(Tt()(pe),be),Pn=at,Un=rt,$n=qe,kn=Be,Fn=He,Nn=Ke,jn=Je,Vn=nt,qn=function(e,t){return Rt(e,t)},Xn=St({addEventListener:!1,Array:!0,Blob:!0,close:!1,CustomEvent:!0,Date:!0,DOMParser:!0,Error:!0,Event:!0,FileReader:!0,KeyboardEvent:!0,location:!0,Math:!0,MouseEvent:!0,MutationEvent:!0,Number:!0,
Object:!0,Promise:!0,ReadableStream:!0,removeEventListener:!1,Uint8Array:!0,XMLHttpRequest:!0}),Bn=(()=>{const e=St({getElementById:Ne,createEvent:je,createElement:Ve,dispatchEvent:Pe,addEventListener,removeEventListener}),t=St({});return Bt(ut(e),(n=>{try{const o=e[n];t[n]=function(...e){return wt(o,Jn.document,e)}}catch(e){t[n]=((e,t)=>{if(zn.error(`Tampermonkey sandbox preparation ${t?"("+t+") ":""}failed. This usually is caused by a third-party extension.`,e),t)return()=>{}
})(e,`document.${n}`)}})),t})(),Hn=St({top:!0,location:!0}),Wn=e,{unsafeWindow:Jn,unsafeThis:Kn}=Wn;e.bridges=e.bridges||St({});const zn=e.console=e.console||St({}),Yn=St({addEventListener:At(ye,Jn),removeEventListener:At(Ee,Jn)});Bt(ut(Hn),(async e=>{if(!Yn[e])try{const t=Jn[e];if(null==t)return;Yn[e]=t}catch(e){}})),Bt(ut(Xn),(async e=>{if(!Yn[e])try{let t=Rt(Jn,e);if(void 0===t&&(Kn===Jn||void 0===(t=Rt(Kn,e))))return;const n=Xn[e];Yn[e]=!1===n&&"function"==typeof t?At(t,Kn):t}catch(e){}}))
;const Qn=e=>{let t,n=[],o=!1;e((e=>{if(!o){if(n.length){const t=n;n=[],Bt(t,(t=>t(e)))}else t=e;o=!0}}));const r=St({then:e=>(o?e(t):qt(n,e),r)});return r},Zn=()=>nn(Dn()+19831206*yt()+1,36),eo=async e=>{await null,e()},{createEvent:to}=Bn,no=(()=>{const{console:t,bridges:n}=e,o=St({});let r;const s=(e,t)=>{let n=[],r=[];const s=()=>{n=[],r=[],a=null,delete o[e]};let a=St({postMessage:n=>{t.send("port.message",St({response_id:e,value:n}))},onMessage:St({addListener:e=>{qt(n,e)}}),
onDisconnect:St({addListener:e=>{qt(r,e)}}),disconnect:()=>{t.send("port.message",St({response_id:e,disconnect:!0})),s()}});return o[e]=St({message:e=>{n&&Bt(n,(t=>t(e)))},disconnect:()=>{r&&Bt(r,(e=>e())),s()}}),a};return St({message:(e,n)=>{let a;if(e.connect){if(!e.destination||!e.response_id)throw"invalid message";r&&r(e.destination,s(e.response_id,n))}else{if(!e.response_id)throw"invalid message";if(!(a=o[e.response_id]))return void t.warn("ports: unkown id",e.response_id,e)
;e.disconnect?a.disconnect():a.message(e.value)}},connect:e=>{const t=Zn();return n.first.send("port.message",St({response_id:t,connect:!0,destination:e})),s(t,n.first)},onConnect:St({addListener:e=>{r=e}})})})(),{bridges:oo}=e,ro=St({}),so=St({});let ao=!0,io=[];eo((()=>{ao=!1,Bt(io,(({m:e,i:t})=>oo.first.send("console",[e,t]))),io=[]})),Bt(["debug","log","info","warn","error"],(e=>{Gt(ro,e,((...t)=>{const n=(e=>{const t=[];return Bt(e,(e=>{qt(t,(e=>xt(e))(e))})),t})(t);if(ao)return qt(io,St({
m:e,i:n}));oo.first.send("console",[e,n])}))}));const lo=St(Mt(Jn.console)),co=St({});Bt(ft(Ge),(e=>{const t=St(lo[e]);co[e]=St({get:"value"in t?()=>t.value:t.get})})),pt(so,co)
;const uo=["chrome"],go=["GM_addElement","GM.addElement","GM_addStyle","GM.addStyle"],po=["GM_cookie","GM.cookie"],vo=["GM_listValues","GM.listValues","GM_getValue","GM.getValue","GM_addValueChangeListener","GM.addValueChangeListener","GM_removeValueChangeListener","GM.removeValueChangeListener"],fo=["GM_setValue","GM.setValue","GM_deleteValue","GM.deleteValue"],mo=["GM_download","GM.download"],_o=["GM_getResourceText","GM.getResourceText","GM_getResourceURL","GM.getResourceUrl"],Mo=["GM_getTab","GM.getTab","GM_getTabs","GM.getTabs","GM_saveTab","GM.saveTab"],bo=["GM_log","GM.log"],ho=["GM_notification","GM.notification"],yo=["GM_openInTab","GM.openInTab"],Eo=["GM_registerMenuCommand","GM.registerMenuCommand","GM_unregisterMenuCommand","GM.unregisterMenuCommand"],wo=["GM_setClipboard","GM.setClipboard"],So=["GM_xmlhttpRequest","GM.xmlHttpRequest"],Go=["window.close"],Oo=["window.focus"],Ro=["window.onurlchange"],Lo=["GM_webRequest","GM.webRequest"],Co=St({
encode:e=>Ae(Oe(e)),decode:e=>Re(Te(e))}),To=St({encode:e=>{let t="";for(let n=0;n<e.length;n++)t+=pn(255&_n(e,n));return xe(t)},decode:e=>Ie(e)}),Ao=e=>{const t=new Nn(e.length);for(let n=0;n<e.length;n++)t[n]=_n(e,n);return t.buffer},Io=(e,t)=>Qn((n=>{const o=new Yn.FileReader;o.onload=()=>{n(un(o))},o.onerror=e=>{zn.warn(`unable to decode data ${e}`),n("")},t?cn(o,e,t):ln(o,e)})),{bridges:xo}=e;let Do=0,Po=0;const Uo=St({}),$o=St({}),ko=function(e,t,n,o){const r=()=>{Uo[n]&&(wt(e,this,o),
delete Uo[n])};"function"==typeof e&&(Uo[n]=e,0===t?eo((()=>r())):xo.first.send("setTimeout",St({t:t||1}),(()=>r())))},Fo=e=>{const t=$o[e];t&&(t.disconnect(),delete $o[e])},No=(e,t,...n)=>{const o=Zn();return ko(e,t,o,n),o},jo=e=>{(e=>{delete Uo[e]})(e)},Vo=e=>Fo(e),qo=(e,t,...n)=>{const o=++Po;return t=Et(t,1),ko(e,t,o,n),o},Xo=(e,t,...n)=>{const o=++Do;return function(e,t,n,o){if("function"==typeof e){const r=$o[n]=no.connect("setInterval");r.onMessage.addListener((()=>{$o[n]&&wt(e,this,o)
})),r.onDisconnect.addListener((()=>Fo(n))),r.postMessage(St({method:"setInterval",t:t||1}))}}(e,t=Et(t,1),o,n),o},Bo=t=>{const{contextId:n,bridges:o}=e,r=St({}),s=(e,t)=>Pt(t,(t=>-1!=Xt(e,t))),a=e=>function(){const t=rn(wt(e,this,arguments));return Gt(t,"then",(e=>sn(t,e))),Gt(t,"catch",(e=>an(t,e))),t},i=(e,t)=>function(...n){const o=[];if(void 0!==t)for(let e=0;e<t;e++)qt(o,qn(n,e)||void 0);return new Yn.Promise((t=>{wt(e,this,Vt(o,[t]))}))},l=(e,t)=>{let n;const o=new Yn.Promise(((o,r)=>{
const s=St({}),a=t.onload,i=t.ontimeout,l=t.onerror;Bt(ut(t),(e=>{s[e]=t[e]})),s.onerror=function(e){r(e),l&&wt(l,this,arguments)},s.ontimeout=function(e){r(e),i&&wt(i,this,arguments)},s.onload=function(e){o(e),a&&wt(a,this,arguments)};const c=e(s).abort;!0===n?c():n=c}));return Gt(o,"abort",(()=>{"function"==typeof n?n():n=!0})),o};return St({of:e=>{const c=e.script,u=(()=>{const e=s(c.grant,wo),t=(e,t,r)=>{o.first.send("setClipboard",St({content:e,info:t,id:n,uuid:c.uuid}),r?()=>r():null)}
;return St({GM_setClipboard:e?St({value:t}):void 0,"GM.setClipboard":e?St({get:()=>i(t,2)}):void 0})})(),d=(()=>{let t=[];const o=e.storage;let r=0,i=null;const l=s(c.grant,vo),u=s(c.grant,fo),d=(e,t)=>{if("string"!=typeof e)return t;{const n=vn(e,0,1);switch(e=vn(e,1),n){case"b":return"true"===e;case"n":return Un(e);case"x":return Co.decode(To.decode(e));case"o":try{return Dt(e)}catch(e){zn.log(`values: parseValueFromStorage: ${e}`)}return t;case"u":return;default:return e}}},g=(e,n,o,r)=>{
n!=o&&Bt(t,(t=>{if(t&&t.key==e&&t.cb)try{t.cb(e,d(n),d(o),r)}catch(t){zn.warn(`values: change listener of "${e}" failed with: ${t.message}`)}}))},p=e=>{i&&i.postMessage(St({method:"saveStorageKey",uuid:c.uuid,key:e,value:o.data[e],id:n,ts:o.ts}))};l&&(i=no.connect("values"),i.onMessage.addListener((e=>{const{storage:t,removed:n}=e;if(!t)return;const r=t.data,s=ut(r);n&&qt(s,n),Bt(s,(e=>{const t=o.data[e],n=r[e];void 0===n?delete o.data[e]:o.data[e]=n,g(e,t,n,!0)}))})),
i.onDisconnect.addListener((()=>{i=null})),i.postMessage(St({method:"addStorageListener",uuid:c.uuid,id:n})));const v=(e,t)=>d(o.data[e],t),f=()=>ut(o.data),m=(e,n)=>{const o=++r,s=St({id:o,key:e,cb:n});return qt(t,s),o},_=e=>{t=Ft(t,(t=>t.id!==e))},M=(e,t)=>{const n=o.data[e];o.ts=Dn(),o.data[e]=(e=>{let t,n=vn(typeof e,0,1);switch(n){case"o":try{t=n+xt(e)}catch(e){return void zn.log(e)}break;case"s":const o=e;-1===fn(o,pn(8232))&&-1===fn(o,pn(8233))||(n="x",t=To.encode(Co.encode(o))),t=n+e
;break;default:t=n+e}return t})(t),p(e),g(e,n,o.data[e],!1)},b=e=>{const t=o.data[e];o.ts=Dn(),delete o.data[e],p(e),g(e,t,o.data[e],!1)};return St({GM_getValue:l?St({value:v}):void 0,"GM.getValue":l?St({get:()=>a(v)}):void 0,GM_listValues:l?St({value:f}):void 0,"GM.listValues":l?St({get:()=>a(f)}):void 0,GM_addValueChangeListener:l?St({value:m}):void 0,"GM.addValueChangeListener":l?St({get:()=>a(m)}):void 0,GM_removeValueChangeListener:l?St({value:_}):void 0,
"GM.removeValueChangeListener":l?St({get:()=>a(_)}):void 0,GM_setValue:u?St({value:M}):void 0,"GM.setValue":u?St({get:()=>a(M)}):void 0,GM_deleteValue:u?St({value:b}):void 0,"GM.deleteValue":u?St({get:()=>a(b)}):void 0})})(),g=(()=>{const e=s(c.grant,Ro),t=(()=>{let e=[],t=null;return St({register:o=>{qt(e,o),t||(t=no.connect("onurlchange"),t.onMessage.addListener((({url:t})=>{t&&Bt(e,(e=>e(St({url:t}))))})),t.postMessage(St({method:"observeUrlChanges",uuid:c.uuid,id:n})))},unregister:n=>{let o
;n&&(o=Xt(e,n))>-1&&(e=Ut(e,o,1).result),t&&0===e.length&&(t.disconnect(),t=null)}})})();return St({"window.onurlchange":e?St({value:t}):void 0})})(),p=(()=>{const e=s(c.grant,_o),t=e=>{for(let t=0;t<c.resources.length;t++){const n=c.resources[t];if(n.name==e){if(n.error)zn.warn("@resource: "+n.error);else try{if("string"==typeof n.content)return Co.decode(n.content)}catch(e){}return""}}return null},n=e=>{for(let t=0;t<c.resources.length;t++){const n=c.resources[t];if(n.name==e){
if(n.error)zn.warn("@resource: "+n.error);else if("string"==typeof n.content){try{return`data:${n.meta||"application/octet-stream"};base64,${To.encode(n.content)}`}catch(e){}return n.url}return""}}return null};return St({GM_getResourceText:e?St({value:t}):void 0,"GM.getResourceText":e?St({get:()=>a(t)}):void 0,GM_getResourceURL:e?St({value:n}):void 0,"GM.getResourceUrl":e?St({get:()=>a(n)}):void 0})})(),v=(()=>{const e=s(c.grant,Mo),t=(e,t)=>{o.first.send("tabs",St({action:"set",uuid:c.uuid,
tab:e}),t?()=>t():null)},n=e=>{o.first.send("tabs",St({action:"get",uuid:c.uuid}),e?t=>{e(t||St({}))}:null)},r=e=>{o.first.send("tabs",St({action:"list",uuid:c.uuid}),e?t=>{e(t||St({}))}:null)};return St({GM_saveTab:e?St({value:t}):void 0,"GM.saveTab":e?St({get:()=>i(t)}):void 0,GM_getTab:e?St({value:n}):void 0,"GM.getTab":e?St({get:()=>i(n)}):void 0,GM_getTabs:e?St({value:r}):void 0,"GM.getTabs":e?St({get:()=>i(r)}):void 0})})(),f=(()=>{const e=s(c.grant,So),o=e=>{const o=Yt(e);let s=!1,a=()=>{
s=!0};const i=(e,t)=>{t=t||St({}),e&&No((()=>{gt(t,r),wt(e,t,[t])}),1)},l=o.url;"object"==typeof l&&l.href&&(o.url=l.href);const u=(e,t)=>{const n=Qt(e);if("Blob"===n||"File"===n){const o=e;Io(o).then((e=>{t(St({type:n,value:e,meta:o.type,name:o.name,lastModified:o.lastModified}))}))}else if("FormData"===n){const n=e,o=n.keys();let r;const s=St({}),a=[];for(;!(r=o.next()).done;)qt(a,r.value);const i=()=>{if(a.length){const e=kt(a);let t=n.getAll(e);"[]"!==vn(e,-2)&&(t=qn(t,0)),u(t,(t=>{s[e]=t,
i()}))}else t(St({type:"FormData",value:s}))};i()}else if("Array"===n||"Object"===n){const o=e;let r,s,a=0,i=0;if("Object"===n){const e=ut(o);s=t=>t<e.length?e[t]:null,r=St({})}else s=e=>e<o.length?e:null,r=[];const l=()=>{const e=s(a);null===e?t(St({type:n,value:r})):u(o[e],(t=>{r[e]=t,a++,i++<1024?l():(i=0,No(l,1))}))};l()}else t(St({value:e}))},d=(e,t,n,o,r)=>{let s;if(n)"stream"==o&&(s=n);else if("arraybuffer"==o)s=t||Ao(e||"");else if("blob"==o)s=new Yn.Blob([t||Ao(e||"")],St({type:r
}));else if("json"==o)s=Dt(e||"");else{if("document"==o){const t=new Yn.DOMParser,n=qn(Wt(r||"text/xml",";"),0);return yn(t,e||"",n)}s=e||(t?(e=>{let t="";const n=new Nn(e);for(let e=0;e<n.length;e+=32687)t+=wt(pn,null,n.subarray(e,e+32687));return t})(t):"")}return s};return(e=>{if(o.url){const t=vn(o.url,0,5);if(-1!=Xt(["data:","blob:"],t))return e()}if(!o.data)return e();u(o.data,(t=>{o.binary&&(t.type="Blob"),o.data=t,o.data_type="typified",e()}))})((()=>{if(s)return s=!1,void i(o.onabort)
;let e,r,l,u=no.connect("xhr"),g=[];const{method:p,url:v,headers:f,cookie:m,binary:_,nocache:M,revalidate:b,timeout:h,context:y,responseType:E,overrideMimeType:w,anonymous:S,fetch:G,user:O,password:R,data:L,data_type:C}=o,T=St({method:p,url:v,headers:f,cookie:m,binary:_,nocache:M,revalidate:b,timeout:h,responseType:E,overrideMimeType:w,anonymous:S,fetch:G,user:O,password:R,data:L,data_type:C});if(T.headers){const e=T.headers;Bt(ut(e),(t=>{"cookie"===Mn(t)&&(T.cookie=`${e[t]}`,delete e[t])}))}
let A,I,x,D;u.postMessage(St({method:"xhr",details:T,callbacks:St({onloadstart:!!o.onloadstart,onload:!!o.onload,ondone:!!o.onloadend,onreadystatechange:!!o.onreadystatechange,onerror:!0,onabort:!!o.onabort,ontimeout:!!o.ontimeout,onprogress:!!o.onprogress,onuploadprogress:!(!o.upload||!o.upload.onprogress),onpartial:!0}),id:n,url:Yn.location.href,uuid:c.uuid,no_blob:"js"==t.sandboxMode}));const P=E?Mn(E):"";let U;const $=async t=>{if(t&&(l||void 0!==e||void 0!==r)){if(w?D=w:t&&(D=(e=>{
const t=St({});return e&&Bt(Wt(e,"\n"),(e=>{const n=Wt(e,":");if(n.length<2)return;const o=qn(n,0);if(!o)return;const r=jt(Nt(n,1),":");t[Mn(mn(o))]=mn(r||"")})),t})(t.responseHeaders)["content-type"]),A=e,l)x=l.stream;else if(r){const e=r;if(I=e.buffer,-1==Xt(["blob","arraybuffer"],P)&&!A){let t;Pt([D,e.type],(e=>t=((e,t,n,o)=>{const r=fn(e,t);if(-1==r)return;const s=vn(e,r+t.length),a=fn(s,";");return-1==a?o&&o.optionalEnd?s:void 0:vn(e,r+t.length,a)})(Mn(e||""),"charset=",0,St({optionalEnd:!0
}))));const n=new Vn([I]);U=Io(n,t),A=await U}U=void 0}else U&&await U;e=r=void 0}if(A||x||I){t.responseType=E,Bt(["response_data"],(e=>delete t[e]));const e=St({response:()=>d(A,I,x,P,D||"binary/octet-stream"),responseText:()=>d(A,I,x,"text",D),responseXML:()=>d(A,I,x,"document","text/xml")});Bt(ut(e),(n=>{vt(t,n,St({get(){try{return e[n]()}catch(e){zn.warn(`${p}:`,e)}}}))}))}},k=[],F=async e=>{e&&qt(k,e);{const e=$t(k);e&&e()}};"stream"===P&&F((async()=>{l=await Qn((e=>{
const t=new Yn.ReadableStream(St({start:n=>{No((()=>e(St({stream:t,ctrl:n}))),0)},cancel:()=>{l&&(l.canceled||a(),l.canceled=!0)}}))}))})),u.onMessage.addListener((t=>F((()=>(async t=>{if(t.onpartial){const n=t.data,o=n,s=o.partial,a=n.nada;if(l){if(l.canceled)return;const e=dn||((e,t)=>e.enqueue(t));if(void 0!==s)e(l.ctrl,s);else if(void 0!==a){const t=new Nn(a.buffer);e(l.ctrl,t)}else zn.error(`${p}:`,"data message without data?!")}else{let t;s&&qt(g,s),a&&(t=a),
void 0!==o.index&&o.index!==o.length-1||(g.length&&(e=jt(g,""),g=[]),r=t)}}else{const e=t.data;if(y&&(e.context=y),t.onload)await $(e),i(o.onreadystatechange,e),i(o.onload,e);else if(t.onreadystatechange)await $(e),4!=e.readyState&&i(o.onreadystatechange,e);else if(t.onerror)t.exception&&zn.error(t.exception),i(o.onerror,e);else if(t.onabort)i(o.onabort,e);else if(t.ondone)l&&!l.canceled&&(gn||(e=>e.close()))(l.ctrl),await $(e),i(o.onloadend,e);else if(t.onloadstart)l&&await $(e),
i(o.onloadstart,e);else if(t.onuploadprogress)o.upload&&i(o.upload.onprogress,e);else{const n=qn(Ft(["onprogress","ontimeout"],(e=>!!t[e])),0)||"onerror";i(o[n],e)}}})(t))))),u.onDisconnect.addListener((()=>u=null)),a=()=>{u&&u.postMessage(St({cancel:!0}))}})),St({abort:()=>{a()}})},r=(()=>{const e=St({DONE:Cn,HEADERS_RECEIVED:Tn,LOADING:An,OPENED:In,UNSENT:xn});return Bt(["text","arraybuffer","blob","document","json","stream"],(t=>{e[`RESPONSE_TYPE_${bn(t)}`]=t})),e})()
;return Bt(ut(r),(e=>Gt(o,e,r[e]))),St({GM_xmlhttpRequest:e?St({value:o}):void 0,"GM.xmlHttpRequest":e?St({get:()=>{const e=e=>l(o,e);return Bt(ut(r),(t=>Gt(e,t,r[t]))),e}}):void 0})})(),m=(()=>{const e=s(c.grant,ho),t=(e,t,r,s)=>{let a=null;const i=["timeout","text","image","title","highlight","silent"],l=St({});if("object"==typeof e){const n=e;Bt(i,(e=>{l[e]=n[e]})),a=n.ondone,s=n.onclick,"function"==typeof t&&(a=t)}else l.image=r,l.text=e,l.title=t
;l.text&&(l.image=l.image||c.icon64||c.icon||void 0,l.title=l.title||c.name),l.onclick=s,l.ondone=a||void 0,(e=>{const{text:t,title:r,image:s,highlight:a,silent:i,timeout:l,onclick:u,ondone:d}=Yt(e),g=St({id:n,uuid:c.uuid,text:t,title:r,image:s,highlight:a,silent:i,timeout:l});t||a?o.first.send("notification",g,(e=>{u&&e.clicked&&u(),d&&d(!0===e.clicked)})):zn.warn("GM_notification: neither a message text nor highlight options were given!")})(l)};return St({GM_notification:e?St({value:t
}):void 0,"GM.notification":e?St({get:()=>(e,n,o,r)=>{let s;return s="object"==typeof e?e:St({text:e,title:n,image:o,onclick:r}),new Yn.Promise((e=>{const n=St({});Bt(ut(s),(e=>{n[e]=s[e]}));const o=n.ondone;n.ondone=function(...t){o&&wt(o,this,t),wt(e,this,t)},t(n)}))}}):void 0})})(),_=(()=>{let n;const o=()=>{if(!n){
const{script:o}=e,{updateURL:r,fileURL:s,grant:a,options:{run_at:i,override:{orig_excludes:l,orig_includes:c,orig_matches:u}}}=o,{version:d,inIncognitoContext:g,isFirstPartyIsolation:p,downloadMode:v}=t,f=St({uuid:1,enabled:1,hash:1,fileURL:1}),m=r||s,_=St({unwrap:!1,"run-at":i,excludes:l,includes:c,matches:u,grant:a}),M=St({scriptMetaStr:o.header,scriptWillUpdate:!!m,scriptUpdateURL:m,version:d,scriptHandler:"Tampermonkey",isIncognito:g,isFirstPartyIsolation:p,downloadMode:v,script:_})
;Bt(ut(o),(e=>{f[e]||(_[e]=o[e])})),n=M}return Dt(xt(n))};return St({GM_info:St({get:o}),"GM.info":St({get:o})})})(),M=(()=>{const e=s(c.grant,Lo);let t=null;const n=(e,n)=>{const o=()=>{t==r&&(t=null),r=null};t&&t.disconnect();let r=t=no.connect("webRequest");return n&&r.onMessage.addListener((e=>{n(e.type,e.message||"ok",e.details)})),r.onDisconnect.addListener(o),r.postMessage(St({rules:e,uuid:c.uuid})),St({abort:()=>{r&&r.disconnect(),o()}})};return St({GM_webRequest:e?St({value:n}):void 0,
"GM.webRequest":e?St({get:()=>a(n)}):void 0})})(),b=(()=>{const e=s(c.grant,Eo);let t=0;const n=St({}),o=(e,o,s)=>{const a=++t,i=no.connect("registerMenuCommand");return i.onMessage.addListener((e=>{if("run"===e.method){const t=e.event,n=t?t.keyCode?new kn("keypress",t):new Fn("click",e.event):void 0;No((()=>o(n)),1)}})),i.onDisconnect.addListener((()=>{r(a)})),i.postMessage(St({method:"register",name:e,uuid:c.uuid,accessKey:s})),n[a]=i.disconnect,a},r=e=>{let t;(t=n[e])&&(t(),delete n[e])}
;return St({GM_registerMenuCommand:e?St({value:o}):void 0,"GM.registerMenuCommand":e?St({get:()=>a(o)}):void 0,GM_unregisterMenuCommand:e?St({value:o}):void 0,"GM.unregisterMenuCommand":e?St({get:()=>a(o)}):void 0})})(),h=(()=>{const e=s(c.grant,po),t=(e,t)=>St({action:e,uuid:c.uuid,url:Yn.location.href,details:t}),n=St({set:(e,n)=>{o.first.send("cookie",t("set",e),n?e=>{n(e.error)}:null)},delete:(e,n)=>{o.first.send("cookie",t("delete",e),n?e=>{n(e.error)}:null)},list:(e,n)=>{
o.first.send("cookie",t("list",e),n?e=>{n(e.cookies,e.error)}:null)}});return St({GM_cookie:e?St({get:()=>{const e=(e,t,o)=>(n[e]||(()=>{}))(t,o);return Bt(ut(n),(t=>{Gt(e,t,n[t])})),e}}):void 0,"GM.cookie":e?St({get:()=>{const e=St({});return Bt(ut(n),(t=>{e[t]=e=>((e,t)=>new Yn.Promise(((o,r)=>{"list"==e?n[e](t,((e,t)=>{t?r(t):o(e)})):n[e](t,(e=>{e?r(e):o(void 0)}))})))(t,e)})),e}}):void 0})})(),y=(()=>{const e=s(c.grant,mo),t=(e,t)=>{const n="object"==typeof e?e:St({url:e,name:t,
headers:void 0,saveAs:void 0,conflictAction:void 0}),o=(e,t)=>{t=t||St({}),e&&No((()=>{wt(e,t,[t])}),1)};let{url:r}=n;const{name:s,headers:a,saveAs:i,conflictAction:l}=n;let u=no.connect("download");return u.onMessage.addListener((e=>{try{e.load?n.onload&&o(n.onload,e.data):e.progress?n.onprogress&&o(n.onprogress,e.data):e.timeout?n.ontimeout&&o(n.ontimeout,e.data):n.onerror&&o(n.onerror,e.data)}catch(e){zn.log("env: Error: TM_download - ",e,n)}})),u.onDisconnect.addListener((()=>u=null)),
Qn((e=>{e()})).then((()=>{if(!u)return;const e=St({details:St({url:r,name:s||"File.download",headers:a,conflictAction:l,saveAs:i}),uuid:c.uuid});u.postMessage(e)})),St({abort:()=>{u&&u.postMessage(St({uuid:c.uuid,cancel:!0}))}})};return St({GM_download:e?St({value:t}):void 0,"GM.download":e?St({get:()=>e=>l(t,e)}):void 0})})(),E=(()=>{const e=s(c.grant,yo),t=(e,t)=>{let n,o,r=!1,s=null;const a=(()=>{const e=[];return St({run:t=>{if(t&&qt(e,t),n)for(;e.length;)kt(e)()}})})()
;let i=no.connect("openInTab");const l=()=>{i&&i.postMessage(St({close:!0}))};i.onMessage.addListener((e=>{e.tabId?r?l():(n=e.tabId,a.run()):e.name?o=e.name:e.closed&&(r=!0,s&&(s(),s=null))})),i.onDisconnect.addListener((()=>i=null)),i.postMessage(St({method:"openTab",url:e,options:t,uuid:c.uuid}));const u=St({});return pt(u,St({close:St({value:()=>{r?zn.warn("env: attempt to close already closed tab!"):l()}}),focus:St({value:()=>{i&&i.postMessage(St({focus:!0}))}}),closed:St({get:()=>r}),
onclose:St({get:()=>s,set:e=>{s=e}}),name:St({get:()=>o,set:e=>{a.run((()=>{i&&i.postMessage(St({name:e}))}))}})})),u};return St({GM_openInTab:e?St({value:t}):void 0,"GM.openInTab":e?St({get:()=>a(t)}):void 0})})(),w=(()=>{const e=s(c.grant,Go);return St({"window.close":e?St({value:e=>{o.first.send("closeTab",St({uuid:c.uuid}),e?()=>e():null)}}):void 0})})(),S=(()=>{const e=s(c.grant,Oo);return St({"window.focus":e?St({value:e=>{o.first.send("focusTab",St({uuid:c.uuid}),e?()=>e():null)}}):void 0
})})(),G=(()=>{const e=s(c.grant,bo),t=function(...e){wt(zn.log,this,e)};return St({GM_log:e?St({value:t}):void 0,"GM.log":e?St({get:()=>a(t)}):void 0})})(),O=({root:e,tag:t,properties:n,cb:r})=>{const s=Zn(),a=St({tag:t,properties:n,id:s,uuid:c.uuid});o.first.send("addElement",a,e,r?()=>r():null);const i=Bn.getElementById(s),l=n?n.id:void 0;return void 0!==l&&Gn(i,"id",l),i},R=(()=>{const e=s(c.grant,go),t=(e,t)=>O(St({root:void 0,tag:"style",properties:St({textContent:e}),cb:t}));return St({
GM_addStyle:e?St({value:t}):void 0,"GM.addStyle":e?St({get:()=>a(t)}):void 0})})(),L=(()=>{const e=s(c.grant,go),t=(e,t,n,o)=>{let r,s,a,i;return"string"==typeof e?(s=e,a=t,i=n):(r=e,s=t,a=n,i=o),a&&(a=St(a)),O(St({root:r,tag:s,properties:a,cb:i}))};return St({GM_addElement:e?St({value:t}):void 0,"GM.addElement":e?St({get:()=>a(t)}):void 0})})(),C=St({...L,...R,...w,...h,...y,...S,..._,...G,...b,...m,...E,...p,...u,...v,...g,...d,...M,...f});return r[e.script.uuid]=r[e.script.uuid]||C,
r[e.script.uuid]}})},Ho=(e,t,n,o,r,s)=>{const a=(e,t,n,o,r)=>{const a=t[n],i=typeof a;return o&&"string"===i?t[n]=()=>s(a,r):r&&"function"===i&&(t[n]=function(){return wt(a,r,arguments)}),wt(e,Jn,t)};let i=!0;eo((()=>i=!1));const l=St({}),c=e=>!!("object"==typeof e&&null!==e?e.capture:e),u=(e,o,r)=>{if("urlchange"!=e||!n["window.onurlchange"]){const n=c(r);let u,d;if(i&&((u="DOMContentLoaded"==e)||"load"==e)){const r=wn(Jn.document)
;if(u&&("complete"==r||"interactive"===r)&&"document-idle"!=t||!u&&"complete"==r)return void(async(e,t,n,o)=>{const r=St({attrName:"null",newValue:"null",prevValue:"null",eventPhase:tn,attrChange:en,target:Jn.document,relatedNode:Jn.document,srcElement:Jn.document});await null,n||await null,"load"===e&&await null,((e,t,n,o)=>{const r=St({attrChange:0,attrName:null,bubbles:!0,cancelBubble:!1,cancelable:!1,clipboardData:void 0,currentTarget:null,defaultPrevented:!1,eventPhase:0,newValue:null,
prevValue:null,relatedNode:null,returnValue:!0,srcElement:null,target:null,timeStamp:Dn()}),a="string"==typeof n?()=>s(n,o):n,i=new Event(e);Bt(ut(r),(e=>{Gt(i,e,r[e])})),Bt(ut(t),(e=>{Gt(i,e,t[e])})),wt(a,o,[i])})(e,r,t,o)})(e,o,n,p)}if("string"==typeof o||"object"==typeof r&&r.once)d=o;else{const t=`${e}-${n}`;l[t]=l[t]||[];const r=function(...e){return wt(o,this===Jn||this===Kn?p:this,e)};qt(l[t],St({listener:o,filter:r})),d=r}return a(Yn.addEventListener,[e,d,r],1,!0)}
n["window.onurlchange"].value.register(o)},d=(e,t,o)=>{if("urlchange"!=e||!n["window.onurlchange"]){const n=c(o),r=`${e}-${n}`,s=l[r]&&Ft(l[r],(e=>e.listener===t));if(s&&s.length){let t;if(Bt(s,(n=>{try{a(Yn.removeEventListener,[e,n.filter,o],1,!0)}catch(n){t=n}const s=Xt(l[r],n);l[r]=Ut(l[r],s,1).result})),l[r].length||delete l[r],t)throw t;return}return a(Yn.removeEventListener,[e,t,o],1,!0)}n["window.onurlchange"].value.unregister(t)},g=St({CDATA:St({value:function(e){this.src=e,
this.toString=function(){return this.src},this.toXMLString=this.toString}}),uneval:St({value:e=>{try{return`\\$1 = ${xt(e)};`}catch(e){zn.log(e)}}}),define:St({value:void 0}),module:St({value:void 0}),exports:St({value:void 0}),setTimeout:St({value:(...e)=>a(qo,e,0,!0,p)}),setInterval:St({value:(...e)=>a(Xo,e,0,!0,p)}),close:(()=>{const e=n["window.close"];return e?St({get:()=>Jn==Jn.top?t=>e.value(t):Yn.close}):void 0})(),focus:(()=>{const e=n["window.focus"];return e?St({get:()=>t=>e.value(t)
}):void 0})(),onurlchange:n["window.onurlchange"]?(()=>{let e=null;return St({get:()=>e,set:t=>{e&&d("urlchange",e),e=t,u("urlchange",e)}})})():void 0,location:St({set:e=>{Yn.location.href=e}}),name:St({get:()=>Jn.name,set:e=>{Jn.name=e}}),clearInterval:St({get:()=>Vo}),clearTimeout:St({get:()=>jo}),addEventListener:St({value:u}),removeEventListener:St({value:d}),console:St({get:()=>so})});if(!e){const e=St({window:St({get:()=>p}),globalThis:St({get:()=>p}),cloneInto:St({value:e=>e}),
exportFunction:St({value:(e,t,n)=>(n&&void 0!==n.defineAs&&(t[n.defineAs]=e),e)}),createObjectIn:St({value:(e,t)=>{const n=St({});return t&&void 0!==t.defineAs&&(e[t.defineAs]=n),n}}),undefined:St({get:()=>{}})});gt(g,e)}o&&gt(g,o);const p=r(g);return p};let Wo;(async()=>{const n=e.contextId;let o;const{fSend:r,fOnMessage:s,pageWindow:a}=e;o=r&&s?(({sendPrefix:e,listenPrefix:t,send:n,onMessage:o})=>{if(void 0===n||void 0===o)throw"invalid args";let r,s,a=1;const i=St({}),l=e=>{e&&(r=e)},c=e=>{
const t=++a;return i[a]=e,t};o(((o,a)=>o==`${t}_${r}`?(t=>{const{m:o,r:a,a:l}=t;if("message.response"==o){if(null==a)throw"Invalid Message";((e,t)=>{let n;e&&(n=i[e])&&(n(t),delete i[e])})(a,l)}else if(s){const i=a?t=>{n(`${e}_${r}`,St({m:"message.response",a:t,r:a}))}:()=>{};s(St({method:o,args:l,node:"MutationEvent"===Qt(t)?Rn(t):void 0}),i)}})(a):null));const u=St({init:async e=>{r?l():l(e)},refresh:()=>null,switchId:e=>{r&&u.cleanup(),l(e)},send:(t,o,s,a)=>{let i,l
;"function"!=typeof s&&null!==s?(i=s,l=a):l=s,n(`${e}_${r}`,St({m:t,a:o,r:l?c(l):null,n:i}))},sendToId:(t,o,r)=>{n(`${e}_${t}`,St({m:o,a:r,r:null}))},setMessageListener:e=>{s=e},cleanup:()=>null});return u})(St({sendPrefix:"2U",listenPrefix:"2S",send:r,onMessage:s})):(({sendPrefix:e,listenPrefix:n,cloneInto:o})=>{let r,s,a,i=1;const l=St({});let c=!1,u=[];const d=e=>{const t=++i;return l[i]=e,t},g=(e,t)=>{const{m:n,a:r,r:s,n:a}=t,i=((e,t,n)=>{let r;var s;return n?(r=to("MutationEvent"),
Zt(r,e,!1,!1,n||null,void 0,void 0,xt(t),en)):r=new $n(e,St({detail:(s=t,o?o(s,Jn.document):s)})),r})(e,St({m:n,a:r,r:s}),a);wt(Pe,Jn,[i])},p=t=>{const{m:n,r:o,a:i}=Yt("CustomEvent"==Qt(d=t)?Ln(d):It(On(d)));var d;if("bridge.onpurge"==n)eo((()=>{a!==Jn.document.documentElement&&m.refresh()}));else if("unlock"==n){c=!1;const e=u;u=[],Bt(e,(e=>e()))}else if("message.response"==n){if(null==o)throw"Invalid Message";((e,t)=>{let n;e&&(n=l[e])&&(n(t),delete l[e])})(o,i)}else if(r){const a=o?t=>{
g(`${e}_${s}`,St({m:"message.response",a:t,r:o}))}:()=>{};r(St({method:n,args:i,node:"MutationEvent"===Qt(t)?Rn(t):void 0}),a)}},v=e=>{e&&(s=e),s&&(a=Jn.document.documentElement,Yn.addEventListener(`${n}_${s}`,p,!0))};let f=()=>{};const m=St({init:async n=>{s?v():v(n),await Qn((e=>{const t=wn(Jn.document);"interactive"==t||"complete"==t?e():Yn.addEventListener("DOMContentLoaded",(()=>{e()}),St({capture:!0,once:!0}))})),t?(a=Jn.document.documentElement,f=()=>{
a!==Jn.document.documentElement&&(m.refresh(),g(`${e}_${s}`,St({m:"unlock",a:void 0,r:null})))}):Qn((e=>{if(t)throw"not supported";{const t=new jn((n=>{Pt(n,(e=>((e,t)=>{for(let n=0,o=e.length;n<o;n++)if(qn(e,n)===t)return!0;return!1})(e.addedNodes,Jn.document.documentElement)))&&(e(Jn.document),t.disconnect())}));t.observe(Jn.document,St({childList:!0}))}})).then((()=>{c=!0,m.send("bridge.onpurge"),m.refresh()}))},refresh:()=>{const e=s;e&&(m.cleanup(),m.init(e))},switchId:e=>{s&&m.cleanup(),
v(e)},send:(n,o,r,a)=>{let i,l;"function"!=typeof r&&null!==r?(i=r,l=a):l=r,t&&f();const p=()=>g(`${e}_${s}`,St({m:n,a:o,r:l?d(l):null,n:i}));c?qt(u,p):p()},sendToId:(t,n,o)=>{g(`${e}_${t}`,St({m:n,a:o,r:null}))},setMessageListener:e=>{r=e},cleanup:()=>{s&&(Yn.removeEventListener(`${n}_${s}`,p,!0),a=void 0,s=void 0)}});return m})(St({sendPrefix:"2C",listenPrefix:"2P"})),e.bridges.first=o,gt(e.console,ro),o.init(n),o.setMessageListener((({method:t,args:n})=>{
"commid"==t?o.switchId(n.id):"setForeignAttr"==t?Jn[n.attr]=n.value:"script"==t?c(n.id,((t,n,o,r)=>{const{pageWindow:s}=e,a=s||Jn,{script:i}=t,l=i.options.compat_powerful_this,c=-1!==Xt(i.grant,"none");Wo=Wo||Bo(n);const u=Wo.of(t),d=e=>St({p:v,r:wt,s:e}),g=St({seed:St({get:()=>d(f),once:!0})}),p=St({}),v=St({GM:p});l&&(Gt(g,"GM",St({value:p})),Gt(g,"unsafeWindow",St({value:a}))),c||(v.unsafeWindow=a),Bt(ut(u),(e=>{const t=vn(e,0,3),n=u[e]
;if(void 0!==n)if("GM_"===t)v[e]=void 0!==n.get?n.get():n.value,l&&Gt(g,e,n);else if("GM."===t){const t=Jt(e,3);vt(p,t,n)}}));const f=c?d(l?v:St({})):Ho(c,i.options.run_at,u,g,o,r);return f})(n.bundle,n.flags,i,u)):"port.message"==t?no.message(n,o):"external.connect"==t&&(()=>{const{bridges:t}=e,n=Ot(Jn,"external");if(!n)return;const o=(e,n)=>{t.first.send("external.message",e,n)};try{pt(n,St({Tampermonkey:St({get:()=>St({getVersion:e=>{o(St({method:"getVersion"}),e)},openOptions:(e,t)=>{o(St({
method:"openOptions",params:e}),t)},isInstalled:(e,t,n)=>{"function"==typeof t&&(n=t,t=null),o(St({method:"isInstalled",script:St({name:e,namespace:t})}),n)}}),configurable:!0})}))}catch(e){}})()}));const{createProxy:i}=((e,t)=>{const n=(e=>{let t=St({});const n=(e,o,r)=>{const s=_t(e);s&&s===o||(null!=s&&--r>=0&&n(s,e,r),t=gt(t,Mt(e)))};return n(e,null,5),t})(Jn);Bt(uo,(e=>delete n[e]));const o=n;return St({createProxy:n=>{let r=o;const s=e=>{let t,n;const o=(t=mt(p,e))||(n=r[e]);return St({
d:o?St(o):o,l:!!t,w:!!n})},a=e=>{if(!l(e))return!1;if("length"===e)return!0;const t=ht(Un(e));return t>=0&&t<=on&&e===`${t}`},i=e=>"on"===vn(e,0,2),l=e=>"string"==typeof e,c=(e,n)=>{const o=vn(e,2),r=g[o];if(r&&(t.removeEventListener(o,r),delete g[o]),n&&(e=>"function"==typeof e)(n)){const e=(...e)=>wt(n,t,e);t.addEventListener(o,e),g[o]=e}},u=t=>void 0!==t&&(t===e||t===Jn||t===Kn),d=St({addEventListener:!0,alert:!0,atob:!0,blur:!0,btoa:!0,cancelAnimationFrame:!0,cancelIdleCallback:!0,
captureEvents:!0,clearInterval:!0,clearTimeout:!0,close:!0,confirm:!0,createImageBitmap:!0,dispatchEvent:!0,dump:!0,fetch:!0,find:!0,focus:!0,getComputedStyle:!0,getDefaultComputedStyle:!0,getSelection:!0,matchMedia:!0,moveBy:!0,moveTo:!0,open:!0,openDatabase:!0,postMessage:!0,print:!0,prompt:!0,queueMicrotask:!0,releaseEvents:!0,removeEventListener:!0,reportError:!0,requestAnimationFrame:!0,requestIdleCallback:!0,resizeBy:!0,resizeTo:!0,scroll:!0,scrollBy:!0,scrollByLines:!0,scrollByPages:!0,
scrollTo:!0,setInterval:!0,setResizable:!0,setTimeout:!0,sizeToContent:!0,stop:!0,structuredClone:!0,updateCommands:!0,webkitCancelAnimationFrame:!0,webkitRequestAnimationFrame:!0,webkitRequestFileSystem:!0,webkitResolveLocalFileSystemURL:!0});Bt(ut(d),(e=>{n[e]=n[e]||St({bind:!0})}));const g=St({}),p=St({});Gt(p,hn,"Window");const v=new Pn(p,St({defineProperty:(e,t,o)=>{const{d:r,l:u}=s(t),d=St(o)
;return r&&!r.configurable&&(!!r.configurable!=!!d.configurable||!!r.enumerable!=!!r.enumerable)||a(t)?(vt(u?p:Jn,t,d),!1):(vt(p,t,d),l(t)&&i(t)&&c(t),delete n[t],!0)},deleteProperty:(e,t)=>{let{d:a,l:u,w:d}=s(t);return!(!a||!a.configurable)&&(u&&(u=delete p[t],l(t)&&i(t)&&c(t)),(d||(a=r[t])&&a.configurable)&&(o===r&&(r=gt(St({}),o)),d=delete r[t]),delete n[t],u||d)},get:(e,t)=>{const o=n[t];if(o){if(o.once&&delete n[t],"value"in o)return o.value;if(o.get)return o.get()}const{d:r,l:i}=a(t)?St({
d:mt(Jn,t),l:!1}):s(t);if(r){let e;const n="value"in r?Ot(r,"value"):(e=Ot(r,"get"))&&"function"==typeof e?i?e():At(e,Jn)():void 0;return n&&o&&o.bind?At(n,Jn):i||"event"==t?n:u(n)||"globalThis"===t?v:n}},getOwnPropertyDescriptor:(e,t)=>{let{d:o,l:r}=s(t);if(!o){const e=n[t];if(e)return St({enumerable:!0,configurable:!0,writable:!0,value:e.value,set:e.set,get:e.get});if(!a(t))return;o=mt(Jn,t),r=!1}const i=gt(St({}),o);if(u(i.value)&&(i.value=v),!r){const e=i.get;e&&(i.get=()=>{
const t=At(e,Jn)();return u(t)?v:t}),i&&!i.configurable&&vt(p,t,i)}return i},has:(e,t)=>t in p||t in n||t in r,ownKeys:()=>{const e=e=>!(e in r),t=ut(r),n=Ft(ut(Mt(p)),e),o=St({});for(let e=0;"Window"===Qt(Rt(Jn,e));e+=1)o[e]=!0;const s=Ft(ut(o),e);return Vt(t,n,s)},preventExtensions:()=>!0,set:(e,t,o)=>{const r=n[t];if(r&&r.set)return r.set(o),!0;const{d:u}=s(t);return!(u&&!u.writable&&!Ot(u,"set")||a(t)||(delete n[t],Gt(p,t,o),l(t)&&i(t)&&c(t,o),0))}}));return v}})})(a,Yn),l=e=>{
o.send("csp",St({src:e}))},c=async(e,t,n)=>{vt(Kn,e,St({set:o=>{delete Kn[e];const r=En(Jn.document);return r&&Sn(r),wt(o,t,n||[])},configurable:!0,enumerable:!1})),eo((()=>delete Kn[e]))},u=(e,t)=>t?((e,t)=>{const n=`__p__${Zn()}`;c(n,t,void 0),l('window["'+n+'"] = function(){'+e+"};"),delete Kn[n]})(e,t):l(e)})()})()};