mouse = true
timestamps = false
messages_limit = 50
attachment_downloads_dir = "/home/chad/Downloads"

[identify]
  user_agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36"
  os = "Linux"
  browser = "Chrome"

[theme]
  background = "black"
  border = "white"
  title = "white"

[keys]
  toggle_guilds_list = "Rune[g]"
  toggle_channels_tree_view = "Rune[c]"
  toggle_messages_text_view = "Rune[m]"
  toggle_message_input_field = "Rune[i]"
  open_message_actions_list = "Rune[a]"
  open_external_editor = "Ctrl+E"
  select_previous_message = "Up"
  select_next_message = "Down"
  select_first_message = "Home"
  select_last_message = "End"
