#!/usr/bin/env bash

icons=("" "" "")

# initial
icon=${icons[$(awk -v n="$(brillo|cut -d. -f1)" 'BEGIN{print int(n/34)}')]}
echo '{ "level": '"$(brillo|cut -d. -f1)"', "icon": "'"$icon"'" }'

udevadm monitor | rg --line-buffered "backlight" | while read -r _; do
  icon="${icons[$(awk -v n="$(brillo|cut -d. -f1)" 'BEGIN{print int(n/34)}')]}"

  echo '{ "level": '"$(brillo|cut -d. -f1)"', "icon": "'"$icon"'" }'
done
