#!/usr/bin/env bash
#
STATUS="$(mpc status)"
COVER="/tmp/.music_cover.png"
MUSIC_DIR="$HOME/Music"

get_status() {
	s=$1
	if [ "$s" = "playing" ]; then
		echo ""
	else
		echo ""
	fi
}

get_length_sec() {
	len=$1
	if [ -z "$len" ]; then
		echo 0
	else
		bc <<< "$len / 1000000"
	fi
}

get_length_time() {
	len=$1
	if [ -n "$len" ]; then
		len=$(bc <<< "$len / 1000000 + 1")
		date -d@"$len" +%M:%S
	else
		echo ""
	fi
}

get_position() {
	pos=$(echo $1 | awk -F: '{ print ($1 * 60) + $2 }')
	len=$(echo $2 | awk -F: '{ print ($1 * 60) + $2 }')
	if [ -n "$pos" ]; then
		bc -l <<< "$pos / $len * 100"
	else
		echo 0
	fi
}

get_position_time() {
	pos=$1
	len=$2
	if [ -n "$pos" ]; then
		date -d@"$(bc <<< "$pos / 1000000")" +%M:%S
	else
		echo ""
	fi
}

# get_cover() {
# 	mkdir -p "$XDG_CACHE_HOME/eww_covers"
# 	cd "$XDG_CACHE_HOME/eww_covers" || exit
#
# 	IMGPATH="$XDG_CACHE_HOME/eww_covers/cover_art.png"
#
# 	playerctl -F metadata mpris:artUrl 2>/dev/null | while read -r COVER_URL; do
# 		if [[ "$COVER_URL" = https* ]]; then
# 			if [ ! -e "$XDG_CACHE_HOME/eww_covers/$(basename "$COVER_URL")" ]; then
# 				wget -N "$COVER_URL" -o /dev/null
# 			fi
#
# 			rm "$IMGPATH"
# 			ln -s "$(basename "$COVER_URL")" "$IMGPATH"
#
# 			IMG="${IMGPATH}"
# 		elif [ "$COVER_URL" = "" ]; then
# 			IMG=""
# 		else
# 			IMG="$COVER_URL"
# 		fi
#
# 		if [ "$IMG" != "" ]; then
# 			cols=$(convert "$IMG" -colors 2 -format "%c" histogram:info: | awk '{print $3}')
# 			color1=$(echo "$cols" | head -1)
# 			color2=$(echo "$cols" | tail -1)
# 		else
# 			color1="#94e2d5"
# 			color2="#89b4fa"
# 		fi
#
# 		jaq --null-input -r -c \
# 			--arg cover "$IMGPATH" \
# 			--arg color1 "$color1" \
# 			--arg color2 "$color2" \
# 			'{"cover": $cover, "color1": $color1, "color2": $color2}'
# 	done
# }

get_cover() {
			color1="#021110"
			color2="#89b4fa"

	ffmpeg -i "${MUSIC_DIR}/$(mpc current -f %file%)" "${COVER}" -y &> /dev/null
	STATUS=$?

	# Check if the file has a embbeded album art
	if [ "$STATUS" -eq 0 ];then
		echo "$COVER"
	else
		echo $COVER = "images/music.png"
	fi
		jaq --null-input -r -c \
			--arg cover "$COVER" \
			--arg color1 "$color1" \
			--arg color2 "$color2" \
			'{"cover": $cover, "color1": $color1, "color2": $color2}'
	# done
}
sanitize() {
	echo "$1" | sed 's/"/\"/g'
}

if [ "$1" = "cover" ]; then
	get_cover
else
mpc -f '%title%\%artist%\%time%\' | head -n 1 2>/dev/null | while IFS="$(printf '\\')" read -r title artist len; do
	# playerctl -F metadata -f '{{title}}\{{artist}}\{{status}}\{{position}}\{{mpris:length}}\' 2>/dev/null | while IFS="$(printf '\\')" read -r title artist status position len; do
	position=$(mpc status | awk 'NR==2 { split($3, a, "/"); print a[1]}')
	status=$(mpc status | awk '/\[/ {print $1}' | sed -E -e 's/\[|\]//g')
		jaq --null-input -r -c \
			--arg artist "$artist" \
			--arg title "$title" \
			--arg status "$(get_status "$status")" \
			--arg pos "$(get_position "$position" "$len")" \
			--arg pos_time "$position" \
			--arg length "$len" \
			'{"artist": $artist, "title": $title, "status": $status, "position": $pos, "position_time": $pos_time, "length": $length}'
	done
fi
			# --arg pos "$position" \
