#!/bin/bash
#
#
STATUS="$(mpc status)"
COVER="/tmp/.music_cover.png"
MUSIC_DIR="$HOME/Music"
get_status() {
	s=$1
	if [ "$s" = "playing" ]; then
		echo ""
	else
		echo ""
	fi
}
get_position() {
	pos=$(echo $1 | awk -F: '{ print ($1 * 60) + $2 }')
	len=$(echo $2 | awk -F: '{ print ($1 * 60) + $2 }')
	if [ -n "$pos" ]; then
		bc -l <<< "$pos / $len * 100"
	else
		echo 0
	fi
}
get_cover() {
			color1="#021110"
			color2="#89b4fa"

	ffmpeg -i "${MUSIC_DIR}/$(mpc current -f %file%)" "${COVER}" -y &> /dev/null
	STATUS=$?
	position=$(mpc status | awk 'NR==2 { split($3, a, "/"); print a[1]}')
	status=$(mpc status | awk '/\[/ {print $1}' | sed -E -e 's/\[|\]//g')
mpc -f '%artist%\%time%\' | head -n 1 2>/dev/null | while IFS="$(printf '\\')" read -r artist len;do

		jaq --null-input -r -c \
			--arg cover "$COVER" \
			--arg color1 "$color1" \
			--arg color2 "$color2" \
			--arg bon "$1" \
			--arg artist "$artist" \
			--arg pos_time "$position" \
			--arg length "$len" \
			--arg status "$(get_status "$status")" \
			--arg pos "$(get_position "$position" "$len")" \
			'{"cover": $cover, "color1": $color1, "color2": $color2, "title": $bon, "position_time": $pos_time, "status": $status, "position": $pos, "artist": $artist, "length": $length }'
		done
}

tmp=""
while true; do	
	title=$(mpc -f '%title%' | head -n 1)
	# mpc -f '%title%\%artist%\%time%\' | head -n 1 | IFS="$(printf '\\')" read -r title artist len
	if [ "$title" != "$tmp" ]; then
		tmp=$title
		# jaq --null-input -r -c \
		# 	--arg artist "artist" \
		# 	--arg title "title" \
		# 	--arg status "status" \
		# 	--arg pos "len" \
		# 	--arg pos_time "position" \
		# 	--arg length "len" \
		# 	'{"artist": $artist, "title": $title, "status": $status, "position": $pos, "position_time": $pos_time, "length": $length}'
	get_cover "$tmp" 

	
	fi

	sleep 3
done

