#!/bin/sh
key=$(xkblayout-state print "%s")

case "$key" in
	"us" )setxkbmap lt
		dunstify "🇱🇹LT" -t  900 -r "92"
		# paplay --volume 30000 ~/.local/share/sounds/'12 - MMX - X Life Gain.wav' ;;
        ;;
	*) 	setxkbmap us
		dunstify "🇺🇸US" -t  900 -r "92"
        ;;
		# paplay --volume 30000 ~/.local/share/sounds/'12 - MMX - X Life Gain.wav' ;;
esac
