#!/bin/sh

# Dependencies - webtorrent, mpv

mkdir -p $HOME/.cache/notflix

menu="rofi -dmenu -i -l 20 -theme ~/.config/scripts/piracy.rasi -multi-select"
baseurl="https://nyaa.si"
cachedir="$HOME/.cache/notflix"

if [ -z $1 ]; then
  query=$(rofi -dmenu -theme ~/.config/scripts/oneline.rasi | cut -d. -f1)
  [ -z $query ] && exit
else
  query=$1
fi

query="$(echo $query | sed 's/ /+/g')"

#curl -s https://1337x.to/category-search/$query/Movies/1/ > $cachedir/tmp.html
curl -s $baseurl/'?f=0&c=1_2&q=$query > $cachedir/tmp.html

# Get Titles
grep -o '<a href="/view/.*</a>' $cachedir/tmp.html |
  sed 's/<[^>]*>//g' > $cachedir/titles.bw

result_count=$(wc -l $cachedir/titles.bw | awk '{print $1}')
if [ "$result_count" -lt 1 ]; then
  notify-send "😔 No Result found. Try again 🔴" -i "NONE"
  exit 0
fi

# Seeders and Leechers
grep -o '<td class="text-center">.*</td>' $cachedir/tmp.html |
  sed 's/<[^>]*>//g' | sed 'N;s/\n/ /' > $cachedir/seedleech.bw

# Size
grep -o '<td class="text-center">.*[MiB][GiB]</td>' $cachedir/tmp.html |
  sed 's/<span class="seeds">.*<\/span>//g' |
  sed -e 's/<[^>]*>//g' > $cachedir/size.bw

# success
# Links
grep -E '<a href="magnet' $cachedir/tmp.html |
  sed -E 's#.*(/magnet/.*)"><.*#\1#' |
  sed 's/<a href="/ /g; s#"><i class="fa fa-fw fa-magnet"></i></a># #g'> $cachedir/links.bw

# Clearning up some data to display
sed 's/Anime/ /g; s/naiyas/ /g; s/GEO/ /g; s/Lia/ /g' $cachedir/titles.bw |
  sed 's/[^A-Za-z0-9 ]//g' | tr -s " " > $cachedir/tmp && mv $cachedir/tmp $cachedir/titles.bw

awk '{print NR " - ["$0"]"}' $cachedir/size.bw > $cachedir/tmp && mv $cachedir/tmp $cachedir/size.bw
awk '{print "[S:"$1 ", L:"$2"]" }' $cachedir/seedleech.bw > $cachedir/tmp && mv $cachedir/tmp $cachedir/seedleech.bw

# Getting the line number
LINE=$(paste -d\   $cachedir/size.bw $cachedir/titles.bw |
  $menu |
  cut -d\- -f1 |
  awk '{$1=$1; print}')

if [ -z "$LINE" ]; then
  notify-send "😔 No Result selected. Exiting... 🔴" -i "NONE"
  exit 0
fi
notify-send "🔍 Searching Magnet seeds 🧲" -i "NONE"
magnet=$(head -n $LINE $cachedir/links.bw | tail -n +$LINE)

# Requesting page for magnet link

qbittorrent "$magnet"


