// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "2d3fbe0c-2847-4fd3-92f0-545524b86471");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1671218186);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1671218004);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1671218233);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1671218261);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1671218216);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{a6e1e3f5-53f2-483d-acfc-7b99c9a467c5}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1671217999);
user_pref("browser.laterrun.bookkeeping.sessionCount", 7);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 133);
user_pref("browser.newtabpage.activity-stream.impressionId", "{0171548e-eec9-49ef-aee1-84b7f1bb6ec1}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1671218001);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1671218192268");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1671219998268");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1671218094415");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1671239694415");
user_pref("browser.search.region", "LT");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20221212233816");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1671218233");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage", "file:///home/chad/.config/firefox/chrome/index.html");
user_pref("browser.startup.homepage_override.buildID", "20221212233816");
user_pref("browser.startup.homepage_override.mstone", "108.0");
user_pref("browser.startup.lastColdStartupCheck", 1671218232);
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"jid1-kkzogwgsw3ao4q_jetpack-browser-action\",\"pywalfox_frewacom_org-browser-action\",\"_8fbc7259-8015-4172-9af1-20e1edfbbd3a_-browser-action\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"jid1-kkzogwgsw3ao4q_jetpack-browser-action\",\"pywalfox_frewacom_org-browser-action\",\"_8fbc7259-8015-4172-9af1-20e1edfbbd3a_-browser-action\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":18,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1671218099555");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "108.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "LT");
user_pref("dom.push.userAgentID", "492e659c44404de091a68e2ecb11f5cf");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20221212233816");
user_pref("extensions.lastAppVersion", "108.0");
user_pref("extensions.lastPlatformVersion", "108.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jid1-KKzOGWgsW3Ao4Q@jetpack", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.pywalfox@frewacom.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{8fbc7259-8015-4172-9af1-20e1edfbbd3a}", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"8a5d2205-806d-47e9-ac65-11eda8e5650b\",\"pictureinpicture@mozilla.org\":\"065b6b01-68e6-4762-a1c8-9c8cc5820a76\",\"screenshots@mozilla.org\":\"47972206-5c99-4b52-bd6d-15e141b04bed\",\"webcompat-reporter@mozilla.org\":\"6990b6f9-3d05-467c-922a-2a9d97c05efe\",\"webcompat@mozilla.org\":\"507ba391-10fc-4edd-bd5e-a94023cb4475\",\"default-theme@mozilla.org\":\"d1baf45d-face-4943-9ce3-0c071f0b7e62\",\"addons-search-detection@mozilla.com\":\"2b280bd8-4090-4a5f-9813-0575dcb777bc\",\"google@search.mozilla.org\":\"8205f9a9-e5ed-4ff5-abfa-f7375af73def\",\"amazondotcom@search.mozilla.org\":\"9d7e1bfb-0e5f-4b01-89ee-f876fcd77764\",\"wikipedia@search.mozilla.org\":\"1d0dd42d-7734-4b54-9754-37cce521558e\",\"bing@search.mozilla.org\":\"deb50b05-122b-4f5d-a202-e5c5346797df\",\"ddg@search.mozilla.org\":\"4e2193e8-4935-40c5-bd03-feb950610582\",\"jid1-KKzOGWgsW3Ao4Q@jetpack\":\"65b9f8fb-100d-4508-a1c7-1f3bbc022ff3\",\"pywalfox@frewacom.org\":\"109bcc09-b061-4e0a-9fa0-86a03a79aa79\",\"{8fbc7259-8015-4172-9af1-20e1edfbbd3a}\":\"c86822ec-72a2-4c73-aeda-84fd1a7ac5e8\",\"uBlock0@raymondhill.net\":\"46777fcf-4518-489c-97d8-1d5e2338648e\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1671218093);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "86dfe061-c070-4a03-aac5-7e281f0a7ecf");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("toolkit.startup.last_success", 1671218230);
user_pref("toolkit.telemetry.cachedClientID", "a9468ae8-ae82-4110-8d3b-20b35ac15434");
user_pref("toolkit.telemetry.previousBuildID", "20221212233816");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
