password = [
    204,
    63,
    180,
    248,
    58,
    248,
    108,
    135,
    247,
    122,
    167,
    213,
    211,
    115,
    20,
    27,
    125,
    248,
    181,
    225,
    52,
    65,
    149,
    37,
    244,
    78,
    249,
    75,
    186,
    202,
    21,
    134,
]
size = [
    5,
    5,
    1910,
    1070,
]
size_ft = [
    0,
    0,
    0,
    0,
]
size_pf = [
    0,
    0,
    0,
    0,
]
view_style = ''
image_quality = ''
custom_image_quality = []
show_remote_cursor = false
lock_after_session_end = false
privacy_mode = false
port_forwards = []
direct_failures = 1
disable_audio = false
disable_clipboard = false
enable_file_transfer = false

[options]

[info]
username = 'iskonsma'
hostname = 'LVMA96178L'
platform = 'Windows'
